name:                durnir
version:             0.1.0.0
github:              "ralphmorton/durnir"
license:             BSD3
author:              "Ralph Morton"
maintainer:          "ralphmorton@gmail.com"
copyright:           "None"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Database

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ralphmorton/durnir#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- directory
- optparse-applicative
- postgresql-simple
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  durnir:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - durnir
